visual_t_a: 0.034
visual_t_b: 0.0385
visual_r_a: 0.0071
visual_r_b: 0.0
visual_scale: 1.0084
odom_k_t: 0.0577
odom_k_r: 0.0562
odom_floor_t: 0.002
odom_floor_r: 0.001
pair_t_a: 0.034
pair_t_b: 0.0385
pair_r_a: 0.0071
pair_r_b: 0.0
map_t_a: 0.034
map_t_b: 0.0385
map_r_a: 0.0071
map_r_b: 0.0
gate_inflation: 2.0
