visual_t_a: 0.0273
visual_t_b: 0.0444
visual_r_a: 0.00638
visual_r_b: 0.0
visual_scale: 1.0193
odom_k_t: 0.0577
odom_k_r: 0.0501
odom_floor_t: 0.002
odom_floor_r: 0.001
pair_t_a: 0.0273
pair_t_b: 0.0444
pair_r_a: 0.00638
pair_r_b: 0.0
map_t_a: 0.0273
map_t_b: 0.0444
map_r_a: 0.00638
map_r_b: 0.0
gate_inflation: 2.0
